/** Short hovers for common JSX/HTML tags in .ryx files. */
export const HTML_TAG_DOCS: Record<string, string> = {
  main: 'Contenido principal de la página (landmark).',
  header: 'Cabecera de sección o página.',
  footer: 'Pie de sección o página.',
  nav: 'Bloque de navegación.',
  section: 'Sección temática del documento.',
  article: 'Contenido autocontenido (entrada, card, etc.).',
  aside: 'Contenido tangencial (sidebar).',
  div: 'Contenedor genérico sin semántica.',
  span: 'Contenedor en línea genérico.',
  p: 'Párrafo de texto.',
  h1: 'Encabezado de nivel 1 (un solo `h1` principal por página recomendado).',
  h2: 'Encabezado de nivel 2.',
  h3: 'Encabezado de nivel 3.',
  ul: 'Lista no ordenada.',
  ol: 'Lista ordenada.',
  li: 'Elemento de lista.',
  a: 'Hipervuelo. En apps Ryunix suele preferirse `Link` del core para rutas internas.',
  button: 'Botón. Usa `type="button"` si no envía formulario.',
  form: 'Formulario. Server Actions pueden usarse con `action` en build.',
  input:
    'Campo de entrada. Especifica `type`, `name`, accesibilidad (`label`).',
  img: 'Imagen. Incluye `alt` descriptivo.',
  label: 'Etiqueta asociada a un control de formulario.',
}
