name: "Build Devtools"
on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.26.0
 
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
           

  
      - name: Install dependencies
        run: pnpm install

   
      - name: build devtools
        run: pnpm build:devtools

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v2
        with:
          cmd: build
          source: ./packages/ryunix-devtools
          filename: "{name}-{version}.xpi"
          ignoreFiles: '[ "package.json","package-lock.json","yarn.lock" ]'

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ryunix-devtools.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
