name: "Build Devtools"
on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: build devtools
        working-directory: ./packages/ryunix-devtools
        run: |
          pnpm build

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v2
        with:
          cmd: build
          source: ./packages/ryunix-devtools
          filename: "{name}-{version}.xpi"
          ignoreFiles: '[ "package.json","package-lock.json","yarn.lock" ]'

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ryunix-devtools.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
